# Generated by Django 5.0.1 on 2024-01-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0003_topic_room_host_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
