# Generated by Django 5.0.1 on 2024-02-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0006_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
